version: "3.8"
services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: sample
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/
    networks:
      - elantris

  redis:
    image: redis
    container_name: default_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - elantris

networks:
  elantris:
volumes:
  postgres_db_data:
  redis_data:
